FROM ubuntu:latest
MAINTAINER Rsundar "contact@abc.com"
RUN apt-get update && apt-get install -y openjdk-8-jdk
WORKDIR /usr/local/bin
COPY test-program.jar .
ENTRYPOINT  ["java","-jar","test-program.jar"]      
